import Head from 'next/head';

// Components
import NavbarComponent from '../components/Navbar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>ArchiTalks</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavbarComponent />
    </div>
  );
}
